### ISSUE TITLE
AA support for tri-state

### ISSUE THREAD

**Issue by userquin** [PolymerElements/paper-checkbox#124]
Provide tri-state support, not only true or false checked value, allow mixed:

https://www.w3.org/TR/wai-aria/roles#checkbox

**Comment by notwaldorf** [comment]
We've had an in depth discussion about this on this thread as to why this shouldn't be a property of the checkbox, but a separate element in itself: https://github.com/PolymerElements/paper-checkbox/issues/33

The feature request for a checkable node element is here: https://github.com/PolymerElements/paper-elements/issues/24

**Comment by notwaldorf** [comment]
Re-opening, since this is an a11y issue, not about the tri-state UI.

**Comment by bicknellr** [comment]
I don't think there's any mandate that checkboxes support a mixed state. In fact, there's explicit mention of a dual-state checkbox in the [WAI-ARIA Authoring Practices](https://www.w3.org/TR/wai-aria-practices/#checkbox) document. That being said, I don't understand the opposition to adding a mixed state to paper-checkbox. There might not be a mixed state for checkboxes in the current Material Design spec but are we really going to land that far off if we add one ourselves? It's a rectangle.

**Comment by admwx7** [comment]
Any chance of getting work towards this in the near future?  If there's a design plan I might be able to get some time to contribute a start on it.

**Comment by userquin** [comment]
Here some hints, based on paper-checkbox (1.3.0, not last but...) (copy it to your component and make these changes):

NOTE: I use this element as a selector not as a checkbox input, so I don't need the invalid property, in fact, I only use it in table headers to change context toolbar for selected rows (delete selected row for example). That being said, the invalid property is ignored.

@notwaldorf maybe this can help you ;)...

Modify aria-checked hostAttribute to be a string instead a boolean and add a property called checked :

```javascript

hostAttributes: {
    role: 'checkbox',
    'aria-checked': 'false',
    tabindex: 0
},
...
properties {
	...
	/**
	 * Gets or sets the state, `true` is checked, `false` is unchecked, `mixed` for partially checked.
	 */
	checked: {
	  type: String,
	  value: 'false',
	  reflectToAttribute: true,
	  notify: true,
	  observer: '_checkedChanged'
	}
}
```

Add _checkedChanged method and change _computeCheckboxClass (REMOVE invalid parameter). Also override _activeChanged and _buttonStateChanged methods:

```javascript
_activeChanged: function(active, ariaActiveAttribute) {
  this._changedButtonState();
},
/**
 * Synchronizes the element's `active` and `checked` state.
 */
_buttonStateChanged: function() {
},
_computeCheckboxClass: function (checked) {
    var className = null;
    if (checked === 'true') {
        className = 'checked';
    } else if (checked === 'mixed') {
        className = 'mixed';
    }
    return className;
},
/**
 * Fire `iron-changed` when the checked state changes.
 */
_checkedChanged: function() {
  this.active = this.checked === 'true' || this.checked === 'mixed';
    if (this.checked == 'true') {
      this.setAttribute(this.ariaActiveAttribute, 'true');
    } else if (this.checked == 'mixed') {
      this.setAttribute(this.ariaActiveAttribute, 'mixed');
    } else {
        this.removeAttribute(this.ariaActiveAttribute);
    }
    if (this.hasRipple()) {
     if (this.checked === 'true' || this.checked === 'mixed') {
       this._ripple.setAttribute('checked', '');
     } else {
       this._ripple.removeAttribute('checked');
     }
   }
    this.fire('iron-change');
},
```

Now component styles:

OLD CODE:
```css
#checkbox.checked #checkmark {
	-webkit-animation: checkmark-expand 140ms ease-out forwards;
	animation: checkmark-expand 140ms ease-out forwards;
}
#checkmark {
	position: absolute;
	width: 36%;
	height: 70%;
	border-style: solid;
	border-top: none;
	border-left: none;
	border-right-width: calc(2/15 * var(--calculated-paper-checkbox-size));
	border-bottom-width: calc(2/15 * var(--calculated-paper-checkbox-size));
	border-color: var(--paper-checkbox-checkmark-color, white);
	-webkit-transform-origin: 97% 86%;
	transform-origin: 97% 86%;
	box-sizing: content-box; /* protect against page-level box-sizing */
}
```
NEW CODE:
```css
:host(:not([aria-checked=mixed])) #checkbox.checked #checkmark {
    -webkit-animation: checkmark-expand 140ms ease-out forwards;
    animation: checkmark-expand 140ms ease-out forwards;
}
:host(:not([aria-checked=mixed])) #checkmark {
    position: absolute;
    width: 36%;
    height: 70%;
    border-style: solid;
    border-top: none;
    border-left: none;
    border-right-width: calc(2 / 15 * var(--calculated-paper-checkbox-size));
    border-bottom-width: calc(2 / 15 * var(--calculated-paper-checkbox-size));
    border-color: var(--paper-checkbox-checkmark-color, white);
    -webkit-transform-origin: 97% 86%;
    transform-origin: 97% 86%;
    box-sizing: content-box; /* protect against page-level box-sizing */
}
```

Add this new styles for mixed box:

```css
:host([aria-checked=mixed]) #checkmark {
    border-bottom: 2px solid var(--primary-text-color);
    width: 60%;
    height: 45%;
    margin-left: 3px;
    -webkit-animation: mixed-expand 140ms ease-out forwards;
    animation: mixed-expand 140ms ease-out forwards;
}
@-webkit-keyframes mixed-expand {
    0% {
        -webkit-transform: scale(0, 0);
    }
    100% {
        -webkit-transform: scale(1, 1);
    }
}
@keyframes mixed-expand {
    0% {
        transform: scale(0, 1);
    }
    100% {
        transform: scale(1, 1);
    }
}

```

And finally adjust html, comment invalid arg in _computeCheckboxClass call: 

```html
<div id="checkboxContainer">
  <div id="checkbox" class$="[[_computeCheckboxClass(checked/*, invalid*/)]]">
    <div id="checkmark" class$="[[_computeCheckmarkClass(checked)]]"></div>
  </div>
</div>
```
![imagen](https://cloud.githubusercontent.com/assets/6311119/20242602/8bf4f744-a934-11e6-889c-bacd8cb6733d.png)

![imagen-mixed](https://cloud.githubusercontent.com/assets/6311119/20242604/9616af4c-a934-11e6-96bc-78afb347abce.png)
 
![imagen-checked](https://cloud.githubusercontent.com/assets/6311119/20242608/d2c64ab0-a934-11e6-90d0-ceb94c036f3d.png)
